remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Jacob Hansen's CSE 15L Lab Reports]
description: [Lab reports for Winter 24' CSE 15L at UCSD.]
